################################################################################################
#                                          FarmAdder                                           #
################################################################################################

#true 설정 시 농작물을 뼛가루로 기를 수 있습니다.
뼛가루_사용여부: false

#true 설정 시 농작물을 물로 수확할 수 있습니다.
물_농작물_수확 : true

#true 설정 시 농작물 수확 시 씨앗이 드랍됩니다.
씨앗_드랍여부: true

#true 설정 시 농작물 위 파티클이 표시됩니다.
#파티클_주기 : 파티클을 초 주기로 소환합니다.
#파티클_최대거리 : 파티클이 소환되는 최대 거리를 설정합니다.
파티클_사용여부: true
파티클_종류: "VILLAGER_HAPPY"
파티클_갯수: 1
파티클_주기: 1
파티클_최대거리: 50