################################################################################################
#                                          FarmAdder                                           #
################################################################################################

#true 설정 시 농작물을 뼛가루로 기를 수 있습니다.
뼛가루_사용여부: false

#true 설정 시 농작물 수확 시 씨앗이 드랍됩니다.
씨앗_드랍여부: true

#true 설정 시 농작물 위 파티클이 표시됩니다.
파티클_사용여부: true
파티클_종류: "VILLAGER_HAPPY"
파티클_갯수: 1